apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jlx8ybq4g-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jlx8ybq4g-python 
  name: jlx8ybq4g-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jlx8ybq4g-python 
